import { CharacterClassDefinition } from "./types";

export const SRD_CLASSES: Record<string, CharacterClassDefinition> = {
  fighter: {
    id: "fighter",
    name: "Fighter",
    hitDie: 10,
    primaryAbilities: ["str", "con"],
    savingThrowProficiencies: ["str", "con"],
    armorProficiencies: ["All armor", "Shields"],
    weaponProficiencies: ["Simple weapons", "Martial weapons"],
    description: "A master of martial combat, skilled with a variety of weapons and armor.",
    defaultStartingGear: ["longsword", "chain_mail", "shield", "potion_of_healing"],
  },
  cleric: {
    id: "cleric",
    name: "Cleric",
    hitDie: 8,
    primaryAbilities: ["wis", "con"],
    savingThrowProficiencies: ["wis", "cha"],
    armorProficiencies: ["Light armor", "Medium armor", "Shields"],
    weaponProficiencies: ["Simple weapons"],
    spellcastingAbility: "wis",
    description: "A priestly champion who wields divine magic in service of a higher power.",
    defaultStartingGear: ["warhammer", "chain_mail", "shield", "potion_of_healing"],
  },
  rogue: {
    id: "rogue",
    name: "Rogue",
    hitDie: 8,
    primaryAbilities: ["dex", "int"],
    savingThrowProficiencies: ["dex", "int"],
    armorProficiencies: ["Light armor"],
    weaponProficiencies: ["Simple weapons", "Hand crossbows", "Longswords", "Rapiers", "Shortswords"],
    description: "A scoundrel who uses stealth and trickery to overcome obstacles and enemies.",
    defaultStartingGear: ["shortsword", "dagger", "leather_armor", "thieves_tools", "potion_of_healing"],
  },
  wizard: {
    id: "wizard",
    name: "Wizard",
    hitDie: 6,
    primaryAbilities: ["int", "con"],
    savingThrowProficiencies: ["int", "wis"],
    armorProficiencies: [],
    weaponProficiencies: ["Daggers", "Darts", "Slings", "Quarterstaffs", "Light crossbows"],
    spellcastingAbility: "int",
    description: "A scholarly magic-user capable of manipulating the structures of reality.",
    defaultStartingGear: ["dagger", "potion_of_healing"],
  },
};
