import { ItemDefinition } from "./types";

export const SRD_ITEMS: Record<string, ItemDefinition> = {
  longsword: {
    id: "longsword",
    name: "Longsword",
    category: "weapon",
    rarity: "common",
    cost: "15 gp",
    weightLbs: 3,
    damageDice: "1d8",
    damageType: "slashing",
    weaponRange: "melee",
    properties: ["Versatile (1d10)"],
    description: "A finely balanced steel blade with an etched crossguard.",
  },
  shortsword: {
    id: "shortsword",
    name: "Shortsword",
    category: "weapon",
    rarity: "common",
    cost: "10 gp",
    weightLbs: 2,
    damageDice: "1d6",
    damageType: "piercing",
    weaponRange: "melee",
    properties: ["Finesse", "Light"],
    description: "A nimble thrusting blade favored by skirmishers and scoundrels.",
  },
  dagger: {
    id: "dagger",
    name: "Dagger",
    category: "weapon",
    rarity: "common",
    cost: "2 gp",
    weightLbs: 1,
    damageDice: "1d4",
    damageType: "piercing",
    weaponRange: "melee",
    properties: ["Finesse", "Light", "Thrown (20/60)"],
    description: "A concealable sharp stiletto blade.",
  },
  warhammer: {
    id: "warhammer",
    name: "Warhammer",
    category: "weapon",
    rarity: "common",
    cost: "15 gp",
    weightLbs: 2,
    damageDice: "1d8",
    damageType: "bludgeoning",
    weaponRange: "melee",
    properties: ["Versatile (1d10)"],
    description: "A heavy forged steel hammer bearing holy dwarven runework.",
  },
  shortbow: {
    id: "shortbow",
    name: "Shortbow",
    category: "weapon",
    rarity: "common",
    cost: "25 gp",
    weightLbs: 2,
    damageDice: "1d6",
    damageType: "piercing",
    weaponRange: "ranged",
    properties: ["Ammunition (80/320)", "Two-Handed"],
    description: "A curved yew bow strung with oiled cord.",
  },
  chain_mail: {
    id: "chain_mail",
    name: "Chain Mail",
    category: "armor",
    rarity: "common",
    cost: "75 gp",
    weightLbs: 55,
    baseArmorClass: 16,
    stealthDisadvantage: true,
    description: "Heavy interlocking steel rings worn over quilted gambeson.",
  },
  leather_armor: {
    id: "leather_armor",
    name: "Leather Armor",
    category: "armor",
    rarity: "common",
    cost: "10 gp",
    weightLbs: 10,
    baseArmorClass: 11,
    description: "Stiffened boiled leather offering light, silent protection.",
  },
  shield: {
    id: "shield",
    name: "Steel Heater Shield",
    category: "shield",
    rarity: "common",
    cost: "10 gp",
    weightLbs: 6,
    armorClassBonus: 2,
    description: "A sturdy wooden shield reinforced with hammered iron.",
  },
  potion_of_healing: {
    id: "potion_of_healing",
    name: "Potion of Healing",
    category: "potion",
    rarity: "common",
    cost: "50 gp",
    weightLbs: 0.5,
    healingDice: "2d4+2",
    description: "A shimmering ruby-red liquid that smells faintly of cinnamon. Drinking it heals 2d4 + 2 HP.",
  },
  thieves_tools: {
    id: "thieves_tools",
    name: "Thieves' Tools",
    category: "gear",
    rarity: "common",
    cost: "25 gp",
    weightLbs: 1,
    description: "A leather roll containing lockpicks, small files, fine mirrors, and miniature tweezers.",
  },
};
