import { MonsterStatblock } from "./types";

export const SRD_MONSTERS: Record<string, MonsterStatblock> = {
  goblin: {
    id: "goblin",
    name: "Goblin",
    size: "Small",
    type: "humanoid (goblinoid)",
    alignment: "neutral evil",
    armorClass: 15,
    armorType: "leather armor, shield",
    hitPoints: 7,
    hitDice: "2d6",
    speed: 30,
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    skills: { stealth: 6 },
    senses: "darkvision 60 ft., passive Perception 9",
    languages: "Common, Goblin",
    challengeRating: 0.25,
    experiencePoints: 50,
    specialTraits: [
      {
        name: "Nimble Escape",
        description: "The goblin can take the Disengage or Hide action as a bonus action on each of its turns.",
      },
    ],
    actions: [
      {
        name: "Scimitar",
        type: "melee",
        toHit: 4,
        reachOrRange: "5 ft.",
        target: "one target",
        damageDice: "1d6+2",
        damageType: "slashing",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.",
      },
      {
        name: "Shortbow",
        type: "ranged",
        toHit: 4,
        reachOrRange: "80/320 ft.",
        target: "one target",
        damageDice: "1d6+2",
        damageType: "piercing",
        description: "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
      },
    ],
    portrait: "/assets/images/enemies/goblin.jpg",
  },
  skeleton: {
    id: "skeleton",
    name: "Skeleton Sentinel",
    size: "Medium",
    type: "undead",
    alignment: "lawful evil",
    armorClass: 13,
    armorType: "armor scraps",
    hitPoints: 13,
    hitDice: "2d8+4",
    speed: 30,
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    damageImmunities: ["poison"],
    conditionImmunities: ["poisoned", "exhaustion" as any],
    senses: "darkvision 60 ft., passive Perception 9",
    languages: "understands languages it knew in life but can't speak",
    challengeRating: 0.25,
    experiencePoints: 50,
    actions: [
      {
        name: "Shortsword",
        type: "melee",
        toHit: 4,
        reachOrRange: "5 ft.",
        target: "one target",
        damageDice: "1d6+2",
        damageType: "piercing",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
      },
      {
        name: "Shortbow",
        type: "ranged",
        toHit: 4,
        reachOrRange: "80/320 ft.",
        target: "one target",
        damageDice: "1d6+2",
        damageType: "piercing",
        description: "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.",
      },
    ],
    portrait: "/assets/images/enemies/skeleton.jpg",
  },
  ghoul: {
    id: "ghoul",
    name: "Crypt Ghoul",
    size: "Medium",
    type: "undead",
    alignment: "chaotic evil",
    armorClass: 12,
    armorType: "natural armor",
    hitPoints: 22,
    hitDice: "5d8",
    speed: 30,
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    damageImmunities: ["poison"],
    conditionImmunities: ["charmed", "exhaustion" as any, "poisoned"],
    senses: "darkvision 60 ft., passive Perception 10",
    languages: "Common",
    challengeRating: 1,
    experiencePoints: 200,
    actions: [
      {
        name: "Bite",
        type: "melee",
        toHit: 2,
        reachOrRange: "5 ft.",
        target: "one creature",
        damageDice: "2d6+2",
        damageType: "piercing",
        description: "Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) piercing damage.",
      },
      {
        name: "Claws",
        type: "melee",
        toHit: 4,
        reachOrRange: "5 ft.",
        target: "one target",
        damageDice: "2d4+2",
        damageType: "slashing",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage. Target must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.",
      },
    ],
    portrait: "/assets/images/enemies/ghoul.jpg",
  },
  wight: {
    id: "wight",
    name: "Lord of the Sunken Crypt (Wight)",
    size: "Medium",
    type: "undead",
    alignment: "neutral evil",
    armorClass: 14,
    armorType: "studded leather",
    hitPoints: 45,
    hitDice: "6d8+18",
    speed: 30,
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    skills: { perception: 3, stealth: 4 },
    damageResistances: ["necrotic", "bludgeoning", "piercing", "slashing"],
    damageImmunities: ["poison"],
    conditionImmunities: ["exhaustion" as any, "poisoned"],
    senses: "darkvision 60 ft., passive Perception 13",
    languages: "Common",
    challengeRating: 3,
    experiencePoints: 700,
    specialTraits: [
      {
        name: "Sunlight Sensitivity",
        description: "While in sunlight, the wight has disadvantage on attack rolls and Perception checks relying on sight.",
      },
    ],
    actions: [
      {
        name: "Multiattack",
        type: "melee",
        toHit: 4,
        reachOrRange: "5 ft.",
        target: "two attacks",
        damageDice: "1d8+2",
        damageType: "slashing",
        description: "The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack.",
      },
      {
        name: "Life Drain",
        type: "melee",
        toHit: 4,
        reachOrRange: "5 ft.",
        target: "one creature",
        damageDice: "1d6+2",
        damageType: "necrotic",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6 + 2) necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken.",
      },
      {
        name: "Ancient Longsword",
        type: "melee",
        toHit: 4,
        reachOrRange: "5 ft.",
        target: "one target",
        damageDice: "1d8+2",
        damageType: "slashing",
        description: "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) slashing damage.",
      },
    ],
    portrait: "/assets/images/enemies/wight.jpg",
  },
};
