import { SpellDefinition } from "./types";

export const SRD_SPELLS: Record<string, SpellDefinition> = {
  sacred_flame: {
    id: "sacred_flame",
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 ft.",
    rangeFt: 60,
    components: "V, S",
    duration: "Instantaneous",
    classes: ["Cleric"],
    description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.",
    damageDice: "1d8",
    damageType: "radiant",
    savingThrow: "dex",
  },
  cure_wounds: {
    id: "cure_wounds",
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Touch",
    rangeFt: 5,
    components: "V, S",
    duration: "Instantaneous",
    classes: ["Cleric", "Bard", "Druid", "Paladin", "Ranger"],
    description: "A creature you touch regains hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    healingDice: "1d8",
  },
  guiding_bolt: {
    id: "guiding_bolt",
    name: "Guiding Bolt",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 ft.",
    rangeFt: 120,
    components: "V, S",
    duration: "1 round",
    classes: ["Cleric"],
    description: "A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.",
    damageDice: "4d6",
    damageType: "radiant",
  },
  fire_bolt: {
    id: "fire_bolt",
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 ft.",
    rangeFt: 120,
    components: "V, S",
    duration: "Instantaneous",
    classes: ["Wizard", "Sorcerer"],
    description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage.",
    damageDice: "1d10",
    damageType: "fire",
  },
  magic_missile: {
    id: "magic_missile",
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 ft.",
    rangeFt: 120,
    components: "V, S",
    duration: "Instantaneous",
    classes: ["Wizard", "Sorcerer"],
    description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target.",
    damageDice: "3d4+3",
    damageType: "force",
  },
  shield: {
    id: "shield",
    name: "Shield",
    level: 1,
    school: "Abjuration",
    castingTime: "1 reaction",
    range: "Self",
    rangeFt: 0,
    components: "V, S",
    duration: "1 round",
    classes: ["Wizard", "Sorcerer"],
    description: "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.",
  },
  misty_step: {
    id: "misty_step",
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    rangeFt: 30,
    components: "V",
    duration: "Instantaneous",
    classes: ["Wizard", "Sorcerer", "Warlock"],
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
  },
  spiritual_weapon: {
    id: "spiritual_weapon",
    name: "Spiritual Weapon",
    level: 2,
    school: "Evocation",
    castingTime: "1 bonus action",
    range: "60 ft.",
    rangeFt: 60,
    components: "V, S",
    duration: "1 minute",
    classes: ["Cleric"],
    description: "You create a floating, spectral weapon within range that lasts for the duration. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier.",
    damageDice: "1d8",
    damageType: "force",
  },
  fireball: {
    id: "fireball",
    name: "Fireball",
    level: 3,
    school: "Evocation",
    castingTime: "1 action",
    range: "150 ft.",
    rangeFt: 150,
    components: "V, S, M",
    duration: "Instantaneous",
    classes: ["Wizard", "Sorcerer"],
    description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.",
    damageDice: "8d6",
    damageType: "fire",
    savingThrow: "dex",
  },
};
